# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sha',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
