# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 19:52
from __future__ import unicode_literals

from django.db import migrations
import hasher.sizeChecker


class Migration(migrations.Migration):

    dependencies = [
        ('hasher', '0002_document_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=hasher.sizeChecker.ContentTypeRestrictedFileField(upload_to='documents/'),
        ),
    ]
